alias software 'agenticos-software'
alias apps 'command tuipkg'
alias tpkg 'command tuipkg'
alias tuipkg 'command tuipkg'
alias tgpt-tui 'command tgpt-tui'
alias sgpt-tui 'command sgpt-tui'
alias tui 'command tgpt-tui'
alias tgpt-provider 'command tgpt-tui --provider'
alias tgpt-model 'command tgpt-tui --model'
alias tgpt-mcp 'command tgpt-tui --mcp'
alias tgpt-tools 'command tgpt-tui --tools'
alias tgpt-shell 'command tgpt -s'
alias tgpt-code 'command tgpt -c'
alias tgpt-find 'command tgpt -f'
alias tgpt-img 'command tgpt --img'
alias tgpt-interactive 'command tgpt -i'
alias tgpt-multiline 'command tgpt -m'
alias '..' 'cd ..'
alias '....' 'cd ../..'
alias '......' 'cd ../../..'
alias .3 'cd ../../..'
alias .4 'cd ../../../..'
alias .5 'cd ../../../../..'
alias clr 'command clear'

if command -qs eza
    alias ls 'eza --color=auto --group-directories-first'
    alias ll 'eza -l --color=auto --group-directories-first'
    alias la 'eza -al --color=auto --group-directories-first'
    alias lt 'eza -a --color=auto --group-directories-first'
end
command -qs bat; and alias cat 'bat -pp'
